### ISSUE TITLE
Add tags for generating image thumbnails

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/hammer#19]
Documented in this issue: wvuweb/cleanslate-cms#121

**Comment by zeroedin** [comment]
Just a note:  "Thumbnails" will never be autocreated by hammer.  Images will need to be added to the theme at the size they are to be displayed.

In the future it might be a good idea to implement some 3rd party image service such as http://lorempixel.com/

**Comment by zeroedin** [comment]
Example `mock_data.yml` entry for files:

```YAML
files:
  - filename: 'mnd-logo'
    title: 'some title'
    name: 'some name'
    alt_text: 'some alt text'
    description: 'some description'
    download_url: '../images/mnd-logo.png'
    image_url: '../images/mnd-logo.png'
  - filename: 'wv-gold'
    title: 'some title'
    name: 'some name'
    alt_text: 'some alt text'
    description: 'some description'
    download_url: '../images/wv-gold.png'
    image_url: '../images/wv-gold.png'
```
