### ISSUE TITLE
Support tag page:data

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/hammer#29]
Custom data attributes can be set in the frontmatter of a layout:

```YAML
---
layout: default

custom_data_attributes:
 - api_url
---
```
Then set in CleanSlates page properties.  

That value can then be pulled back into the template using the page:data radius tag:

```XML
<r:page:data name='api_url' />
```

Need the ability to mock this in Hammer via the `mock_data.yml`

```
page:
  id: 2
  name: "Random Page"
  ...
  data:
    api_url: http://someurl-to.some-api.ontheweb.com
```
