### ISSUE TITLE
Add support for pulling in multiple editable regions on a blog index page.

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/hammer#37]
Right now, we can call in `content` for your blog index page, like this:

```yaml
blog:
  name: 25 Days of Giveaways
  articles:
    - article:
      name: <%= Faker::Lorem.sentence(1) %>
      title: <%= Faker::Lorem.sentence(1) %>
      created_by:
        first_name: <%= Faker::Name.first_name %>
      published_at: 2 days ago
      content: Yo Bro!
```

But, if you want to separate the `content` key to call **multiple** editable regions, it doesn't work at this moment. Code example:

```yaml
blog:
  name: 25 Days of Giveaways
  articles:
    - article:
      name: <%= Faker::Lorem.sentence(1) %>
      title: <%= Faker::Lorem.sentence(1) %>
      created_by:
        first_name: <%= Faker::Name.first_name %>
        last_name: <%= Faker::Name.last_name %>
      published_at: 2 days ago
      content:
        article__short-desc: This is the short description editable region.
        article__long-desc: Long description editable region.
```

Here's a screenshot of the output:

![blog-index-editable-regions](https://cloud.githubusercontent.com/assets/575865/11225368/cdb6be6a-8d47-11e5-8093-00a9f77fad52.png)

Using Hammer VM on OSX 10.10.5 (Yosemite).
