### ISSUE TITLE
Add support for r:site:data

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/hammer#42]
Add support for the `<r:site:data name="my-name" />` tag. Brand Patterns now uses this for Google Site Verification out of the box (for Google Search Console / Webmaster Tools). Here's the relevant commit from Brand Patterns:

https://github.com/wvuweb/brand-patterns/commit/e662943a75f658460f93b4618f0b810ed049674d?w=0

You should be able to clone [Brand Patterns](https://github.com/wvuweb/brand-patterns) and use that theme for testing.

Here's a site key to copy and paste into your `mock_data.yml`:

```yaml
site:
  name: "Brand Patterns"
  data:
    google_site_verification: yo-dog
```

#29 is related to this issue.
