### ISSUE TITLE
Implement <r:page:url />  

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/hammer#6]
This tag is used to link pages inside of tags such as:  `<r:page:previous_sibling>` & `<r:page:next_sibling>` tags

Use case example:

``` html
<r:page:next_sibling>
    <li><a class="arrow__next" href="<r:page:url />">Next Page</a></li>
</r:page:next_sibling>
```

By default the page:url attribute should return the current request: `http://localhost:2000/theme/view.html`

The attribute should also be available to override in the `mock_data.yml`

``` yml
page:
  name: Example
  url: http://www.google.com
```
