### ISSUE TITLE
Shared themes should default to the code repository

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/hammer#7]
If a user has the shared masthead or footer being served from the `code` repository, hammer shouldn't have to be configured to point to the `code` repo via the `mock_data.yml` file. In other words, this:

``` yaml
shared_themes:
  layouts__masthead--v1: "code"
  layouts__footer__contact--v1: "code"
  layouts__footer__credits--v1: "code"
  layouts__footer__icons--v1: "code"
  layouts__browser-update-org--v1: "code"
```

...shouldn't be required. Hammer should assume these shared themes will be served from the `code` repo. 

Now, let's say Eberly has a shared partial or something, once someone writes out `shared_themes` in the mock data file, that's when this stuff must be configured.
