### ISSUE TITLE
Add the ability to use tag attribute on blogs

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/hammer#70]
Add the ability to use the tag attribute on blog articles.  Support the use of tag_ops attribute as well

Example:

```
<r:blog:articles limit="1" tags="feature-one, feature" tags_op="any">
```

Mock Data Example
```yml
- article:
  id: "22"
  name: "<%= Faker::Lorem.sentence(1) %>"
  title: "<%= Faker::Lorem.sentence(1) %>"
  tags:
    - "feature-one"
```
